name: Mobile CI

on:
  workflow_dispatch:
    inputs:
      browser_type:
        description: 'Select the browser type'
        required: true
        default: 'chromium'  # Default value
        options:
          - chromium
          - firefox
          - webkit
      base_url:
        description: 'Base URL for testing'
        required: true
        default: 'https://www.devchallenge.it/'  # Default value

jobs:
  test:
    runs-on: ubuntu-latest  # The runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify your desired Python version
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwoff2dec1 \
            libvpx7 \
            libevent-2.1-7 \
            libopus0 \
            libgstreamer1.0-0 \
            libgstreamer-plugins-base1.0-0 \
            libharfbuzz0b \
            libhyphen0 \
            libmanette-0.2-0 \
            libflite1 \
            libgles2 \
            libx264-152 \
            libglib2.0-0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure you have a requirements.txt file

      - name: Install Playwright browsers
        run: |
          playwright install  # Download the necessary browser binaries

      - name: Set environment variables for Mobile
        run: |
          echo "BROWSER_TYPE=${{ github.event.inputs.browser_type }}" >> $GITHUB_ENV
          echo "BASE_URL=${{ github.event.inputs.base_url }}" >> $GITHUB_ENV
          echo "PLATFORM=mobile" >> $GITHUB_ENV
          echo "HEADLESS=true" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest -s -v -m $PLATFORM  # Run tests for mobile

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: desktop-test-results
          path: ./reports/report.html
